# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Docker Integration Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Start 4 node docker cluster
        run: make clean && make docker-cluster-start &

      - name: Wait for docker cluster to start
        run: |
          until [ $(cat build/generated/launch.complete |wc -l) = 4 ]
          do
            sleep 10
          done
          sleep 5

      - name: Verify Sei Chain is able to start up
        run: docker exec -i sei-node-0 integration_test/startup/startup_test.sh

      - name: Testing Dex Module
        run: docker exec -i sei-node-0 integration_test/dex_module/place_order_test.sh

      - name: Testing Wasm Module
        run: |
          docker exec -i sei-node-0 integration_test/contracts/deploy_timelocked_token_contract.sh
          docker exec -i sei-node-0 integration_test/wasm_module/timelocked_token_test_1.sh
          docker exec -i sei-node-0 integration_test/contracts/deploy_timelocked_token_contract.sh
          docker exec -i sei-node-0 integration_test/wasm_module/timelocked_token_test_2.sh
          docker exec -i sei-node-0 integration_test/contracts/deploy_timelocked_token_contract.sh migration
          docker exec -i sei-node-0 integration_test/wasm_module/timelocked_token_test_3.sh
